export const sampleProperties = [
  {
    title: 'Luxury Villa with Private Pool',
    description: 'An architectural masterpiece in the serene enclave of Kokapet. Features double-height ceilings, private infinity plunge pool, Italian marble flooring, and smart home automation throughout.',
    propertyType: 'Villa',
    listingType: 'Sale',
    price: 18000000,
    priceFormatted: '₹1.80 Cr',
    location: 'Kokapet',
    city: 'Hyderabad',
    bedrooms: 4,
    bathrooms: 5,
    areaSqft: 3200,
    status: 'Available',
    primaryImage: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: ['Private Pool', 'Clubhouse', 'Home Automation', 'EV Charging', '24/7 Security', 'Lush Garden'],
    virtualTourUrl: 'https://example.com/tour/kokapet-villa',
    featured: true,
    verified: true,
    agentName: 'Rajesh Varma',
    agentPhone: '+91 98490 11223',
  },
  {
    title: 'Modern 3 BHK Sunset Apartment',
    description: 'Located in the tech core of Gachibowli, this north-east facing apartment offers breathtaking skyline views, modular German kitchen, and direct access to top international schools and tech parks.',
    propertyType: 'Apartment',
    listingType: 'Sale',
    price: 8500000,
    priceFormatted: '₹85 Lakhs',
    location: 'Gachibowli',
    city: 'Hyderabad',
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 1850,
    status: 'Available',
    primaryImage: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: ['Gymnasium', 'Covered Car Parking', 'Power Backup', 'Children Play Area', 'Rooftop Lounge'],
    virtualTourUrl: 'https://example.com/tour/gachibowli-3bhk',
    featured: true,
    verified: true,
    agentName: 'Priya Sharma',
    agentPhone: '+91 98492 33445',
  },
  {
    title: 'Premium 2 BHK Sunlit Flat',
    description: 'Cozy and contemporary home in Kondapur near Botanical Garden. Thoughtfully designed with cross-ventilation, expansive balconies, and premium sanitary fittings.',
    propertyType: 'Apartment',
    listingType: 'Sale',
    price: 6500000,
    priceFormatted: '₹65 Lakhs',
    location: 'Kondapur',
    city: 'Hyderabad',
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1280,
    status: 'Available',
    primaryImage: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: ['Jogging Track', '24/7 Security', 'High-Speed Elevators', 'Clubhouse'],
    virtualTourUrl: '',
    featured: true,
    verified: true,
    agentName: 'Vikram Reddy',
    agentPhone: '+91 98495 55667',
  },
  {
    title: 'Sky Penthouse with Panoramic Terrace',
    description: 'Ultra-exclusive 4 BHK penthouse overlooking Durgam Cheruvu and the Financial District. Features private elevator access, glass railings, and custom designer finishes.',
    propertyType: 'Apartment',
    listingType: 'Sale',
    price: 32000000,
    priceFormatted: '₹3.20 Cr',
    location: 'Financial District',
    city: 'Hyderabad',
    bedrooms: 4,
    bathrooms: 5,
    areaSqft: 4100,
    status: 'Available',
    primaryImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: ['Private Elevator', 'Infinity Pool', 'Concierge Service', 'Helipad Access', 'Wine Cellar'],
    virtualTourUrl: 'https://example.com/tour/financial-sky-penthouse',
    featured: false,
    verified: true,
    agentName: 'Rajesh Varma',
    agentPhone: '+91 98490 11223',
  },
  {
    title: 'Serene Heritage House in Jubilee Hills',
    description: 'Expansive private bungalow surrounded by mature teak and neem trees in prestigious Road No. 36 Jubilee Hills. Large lawns, courtyard, and multi-vehicle garage.',
    propertyType: 'House',
    listingType: 'Sale',
    price: 45000000,
    priceFormatted: '₹4.50 Cr',
    location: 'Jubilee Hills',
    city: 'Hyderabad',
    bedrooms: 5,
    bathrooms: 6,
    areaSqft: 5200,
    status: 'Available',
    primaryImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: ['Sprawling Lawn', 'Staff Quarters', 'Solar Power', 'Security Cameras', 'Covered Porch'],
    virtualTourUrl: '',
    featured: false,
    verified: true,
    agentName: 'Priya Sharma',
    agentPhone: '+91 98492 33445',
  },
  {
    title: 'Fully Furnished Executive Rental Flat',
    description: 'Designed for corporate professionals in Hitec City. High floor with uninterrupted views, walk-in closets, central AC, and all appliances included.',
    propertyType: 'Apartment',
    listingType: 'Rent',
    price: 48000,
    priceFormatted: '₹48,000 / mo',
    location: 'Hitec City',
    city: 'Hyderabad',
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1350,
    status: 'Available',
    primaryImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: ['Fully Furnished', 'Wi-Fi Ready', 'Gym & Pool Access', 'Housekeeping Service'],
    virtualTourUrl: '',
    featured: false,
    verified: true,
    agentName: 'Vikram Reddy',
    agentPhone: '+91 98495 55667',
  }
];
